// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include "../inst/include/FLRcppAdolc.h"

using namespace Rcpp;

// test_assignment_operator
FLQuant test_assignment_operator(FLQuant flq1);
RcppExport SEXP FLRcppAdolc_test_assignment_operator(SEXP flq1SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    FLQuant flq1 = Rcpp::as<FLQuant >(flq1SEXP);
    FLQuant __result = test_assignment_operator(flq1);
    return Rcpp::wrap(__result);
END_RCPP
}
