// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include "../inst/include/FLRcppAdolc.h"

using namespace Rcpp;

// do_nothing_FLQuantAdolc
void do_nothing_FLQuantAdolc();
RcppExport SEXP FLRcppAdolc_do_nothing_FLQuantAdolc() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    do_nothing_FLQuantAdolc();
    return R_NilValue;
END_RCPP
}
// do_nothing_FLQuant
void do_nothing_FLQuant();
RcppExport SEXP FLRcppAdolc_do_nothing_FLQuant() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    do_nothing_FLQuant();
    return R_NilValue;
END_RCPP
}
// test_FLQuant_basic_constructor
void test_FLQuant_basic_constructor();
RcppExport SEXP FLRcppAdolc_test_FLQuant_basic_constructor() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test_FLQuant_basic_constructor();
    return R_NilValue;
END_RCPP
}
// test_FLQuant_sexp_constructor
void test_FLQuant_sexp_constructor(SEXP flq_sexp);
RcppExport SEXP FLRcppAdolc_test_FLQuant_sexp_constructor(SEXP flq_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    SEXP flq_sexp = Rcpp::as<SEXP >(flq_sexpSEXP);
    test_FLQuant_sexp_constructor(flq_sexp);
    return R_NilValue;
END_RCPP
}
// test_FLQuant_as_wrap
FLQuant test_FLQuant_as_wrap(FLQuant flq);
RcppExport SEXP FLRcppAdolc_test_FLQuant_as_wrap(SEXP flqSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    FLQuant flq = Rcpp::as<FLQuant >(flqSEXP);
    FLQuant __result = test_FLQuant_as_wrap(flq);
    return Rcpp::wrap(__result);
END_RCPP
}
// test_mult
void test_mult();
RcppExport SEXP FLRcppAdolc_test_mult() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test_mult();
    return R_NilValue;
END_RCPP
}
