# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run <- function(fisheries, biol, srr_model_name, srr_params, srr_residuals, srr_residuals_mult, f) {
    .Call('FLRcppAdolc_run', PACKAGE = 'FLRcppAdolc', fisheries, biol, srr_model_name, srr_params, srr_residuals, srr_residuals_mult, f)
}

test_project_timestep <- function(fisheries, biol, srr_model_name, params, residuals, residuals_mult, f, timestep) {
    .Call('FLRcppAdolc_test_project_timestep', PACKAGE = 'FLRcppAdolc', fisheries, biol, srr_model_name, params, residuals, residuals_mult, f, timestep)
}

test_FLQuant_FLQuant_multiplier_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_multiplier_assignment_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuantAdolc_FLQuantAdolc_multiplier_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_multiplier_assignment_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuantAdolc_double_multiplier_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuantAdolc_adouble_multiplier_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuant_FLQuant_multiplier_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_multiplier_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_multiplier_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuant_FLQuantAdolc_multiplier_operator <- function(flq1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuantAdolc_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, flqad2)
}

test_FLQuantAdolc_FLQuantAdolc_multiplier_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_multiplier_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_multiplier_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_double_FLQuant_multiplier_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuant_multiplier_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_double_FLQuantAdolc_multiplier_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuantAdolc_multiplier_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_double_multiplier_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuant_adouble_multiplier_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_adouble_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuant_multiplier_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuant_multiplier_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_adouble_multiplier_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuantAdolc_multiplier_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuantAdolc_multiplier_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuant_FLQuant_division_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_division_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_division_assignment_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_division_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuantAdolc_FLQuantAdolc_division_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_division_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_division_assignment_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_division_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuantAdolc_double_division_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_division_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuantAdolc_adouble_division_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_division_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuant_FLQuant_division_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_division_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_division_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_division_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuant_FLQuantAdolc_division_operator <- function(flq1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuantAdolc_division_operator', PACKAGE = 'FLRcppAdolc', flq1, flqad2)
}

test_FLQuantAdolc_FLQuantAdolc_division_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_division_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_division_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_division_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_double_FLQuant_division_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuant_division_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_double_FLQuantAdolc_division_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuantAdolc_division_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_double_division_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_division_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuant_adouble_division_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_adouble_division_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuant_division_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuant_division_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_adouble_division_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_division_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuantAdolc_division_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuantAdolc_division_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuant_FLQuant_subtraction_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_subtraction_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_subtraction_assignment_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_subtraction_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuantAdolc_FLQuantAdolc_subtraction_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_subtraction_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_subtraction_assignment_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_subtraction_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuantAdolc_double_subtraction_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_subtraction_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuantAdolc_adouble_subtraction_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_subtraction_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuant_FLQuant_subtraction_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_subtraction_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_subtraction_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_subtraction_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuant_FLQuantAdolc_subtraction_operator <- function(flq1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuantAdolc_subtraction_operator', PACKAGE = 'FLRcppAdolc', flq1, flqad2)
}

test_FLQuantAdolc_FLQuantAdolc_subtraction_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_subtraction_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_subtraction_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_subtraction_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_double_FLQuant_subtraction_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuant_subtraction_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_double_FLQuantAdolc_subtraction_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuantAdolc_subtraction_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_double_subtraction_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_subtraction_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuant_adouble_subtraction_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_adouble_subtraction_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuant_subtraction_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuant_subtraction_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_adouble_subtraction_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_subtraction_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuantAdolc_subtraction_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuantAdolc_subtraction_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuant_FLQuant_addition_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_addition_assignment_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuantAdolc_FLQuantAdolc_addition_assignment_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_addition_assignment_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuantAdolc_double_addition_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuantAdolc_adouble_addition_assignment_operator <- function(flqad1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flqad1, value)
}

test_FLQuant_FLQuant_addition_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_addition_operator <- function(flqad1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_addition_operator', PACKAGE = 'FLRcppAdolc', flqad1, flq2)
}

test_FLQuant_FLQuantAdolc_addition_operator <- function(flq1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuantAdolc_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, flqad2)
}

test_FLQuantAdolc_FLQuantAdolc_addition_operator <- function(flqad1, flqad2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_addition_operator', PACKAGE = 'FLRcppAdolc', flqad1, flqad2)
}

test_FLQuant_double_addition_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_double_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_double_FLQuant_addition_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuant_addition_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_double_FLQuantAdolc_addition_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_double_FLQuantAdolc_addition_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_double_addition_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_double_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_FLQuant_adouble_addition_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuant_adouble_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuant_addition_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuant_addition_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuantAdolc_adouble_addition_operator <- function(flq1, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_adouble_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, value)
}

test_adouble_FLQuantAdolc_addition_operator <- function(value, flq1) {
    .Call('FLRcppAdolc_test_adouble_FLQuantAdolc_addition_operator', PACKAGE = 'FLRcppAdolc', value, flq1)
}

test_FLQuant_log <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_log', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_log <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_log', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_exp <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_exp', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_exp <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_exp', PACKAGE = 'FLRcppAdolc', flq)
}

test_composite_arithmetic_operators <- function(flqad, flq, value) {
    .Call('FLRcppAdolc_test_composite_arithmetic_operators', PACKAGE = 'FLRcppAdolc', flqad, flq, value)
}

test_FLQuant_quant_sum <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_quant_sum', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_quant_sum <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_quant_sum', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_max_quant <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_max_quant', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_max_quant <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_max_quant', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_scale_by_max_quant <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_scale_by_max_quant', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_scale_by_max_quant <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_scale_by_max_quant', PACKAGE = 'FLRcppAdolc', flq)
}

test_simple_FLCatch_sexp_constructor <- function(flc_sexp) {
    .Call('FLRcppAdolc_test_simple_FLCatch_sexp_constructor', PACKAGE = 'FLRcppAdolc', flc_sexp)
}

test_FLCatch_sexp_constructor <- function(flc_sexp) {
    .Call('FLRcppAdolc_test_FLCatch_sexp_constructor', PACKAGE = 'FLRcppAdolc', flc_sexp)
}

test_FLCatchAdolc_sexp_constructor <- function(flc_sexp) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_sexp_constructor', PACKAGE = 'FLRcppAdolc', flc_sexp)
}

test_FLCatch_as_wrap <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_as_wrap', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_as_wrap <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_as_wrap', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_copy_constructor <- function(flc1) {
    .Call('FLRcppAdolc_test_FLCatch_copy_constructor', PACKAGE = 'FLRcppAdolc', flc1)
}

test_FLCatchAdolc_copy_constructor <- function(flc1) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_copy_constructor', PACKAGE = 'FLRcppAdolc', flc1)
}

test_FLCatch_copy_constructor2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatch_copy_constructor2', PACKAGE = 'FLRcppAdolc', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatchAdolc_copy_constructor2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_copy_constructor2', PACKAGE = 'FLRcppAdolc', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatch_assignment_operator <- function(flc1) {
    .Call('FLRcppAdolc_test_FLCatch_assignment_operator', PACKAGE = 'FLRcppAdolc', flc1)
}

test_FLCatchAdolc_assignment_operator <- function(flc1) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_assignment_operator', PACKAGE = 'FLRcppAdolc', flc1)
}

test_FLCatch_assignment_operator2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatch_assignment_operator2', PACKAGE = 'FLRcppAdolc', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatchAdolc_assignment_operator2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_assignment_operator2', PACKAGE = 'FLRcppAdolc', flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatch_const_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatch_const_get_accessors', PACKAGE = 'FLRcppAdolc', flc, quant, year, unit, season, area, iter)
}

test_FLCatchAdolc_const_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_const_get_accessors', PACKAGE = 'FLRcppAdolc', flc, quant, year, unit, season, area, iter)
}

test_FLCatch_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatch_get_accessors', PACKAGE = 'FLRcppAdolc', flc, quant, year, unit, season, area, iter)
}

test_FLCatchAdolc_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_get_accessors', PACKAGE = 'FLRcppAdolc', flc, quant, year, unit, season, area, iter)
}

test_FLCatch_set_accessors <- function(flc, quant, year, unit, season, area, iter, values) {
    .Call('FLRcppAdolc_test_FLCatch_set_accessors', PACKAGE = 'FLRcppAdolc', flc, quant, year, unit, season, area, iter, values)
}

test_FLCatchAdolc_set_accessors <- function(flc, quant, year, unit, season, area, iter, values) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_set_accessors', PACKAGE = 'FLRcppAdolc', flc, quant, year, unit, season, area, iter, values)
}

test_FLCatch_landings <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_landings', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_landings <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_landings', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_discards <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_discards', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_discards <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_discards', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_catch_n <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_catch_n', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_catch_n <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_catch_n', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_catch_wt <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_catch_wt', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_catch_wt <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_catch_wt', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_catches <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_catches', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_catches <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_catches', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_discards_ratio <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_discards_ratio', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_discards_ratio <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_discards_ratio', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_landings_sel <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_landings_sel', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_landings_sel <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_landings_sel', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatch_discards_sel <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatch_discards_sel', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchAdolc_discards_sel <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchAdolc_discards_sel', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatches_as_wrap <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatches_as_wrap', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatches_sexp_constructor <- function(flcs_sexp1) {
    .Call('FLRcppAdolc_test_FLCatches_sexp_constructor', PACKAGE = 'FLRcppAdolc', flcs_sexp1)
}

test_FLCatches_FLCatch_constructor <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatches_FLCatch_constructor', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatches_copy_constructor <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatches_copy_constructor', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatches_copy_constructor2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatches_copy_constructor2', PACKAGE = 'FLRcppAdolc', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatches_assignment_operator <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatches_assignment_operator', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatches_assignment_operator2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatches_assignment_operator2', PACKAGE = 'FLRcppAdolc', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatches_function_operator <- function(flcs, flc) {
    .Call('FLRcppAdolc_test_FLCatches_function_operator', PACKAGE = 'FLRcppAdolc', flcs, flc)
}

test_FLCatches_get_ncatches <- function(flc_sexp1) {
    .Call('FLRcppAdolc_test_FLCatches_get_ncatches', PACKAGE = 'FLRcppAdolc', flc_sexp1)
}

test_FLCatches_const_get_single_index_accessor <- function(flcs, element) {
    .Call('FLRcppAdolc_test_FLCatches_const_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flcs, element)
}

test_FLCatches_get_single_index_accessor <- function(flcs, element) {
    .Call('FLRcppAdolc_test_FLCatches_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flcs, element)
}

test_FLCatches_const_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatches_const_get_value_accessor', PACKAGE = 'FLRcppAdolc', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatches_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatches_get_value_accessor', PACKAGE = 'FLRcppAdolc', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatches_set_single_index_accessor <- function(flcs, element, flc) {
    .Call('FLRcppAdolc_test_FLCatches_set_single_index_accessor', PACKAGE = 'FLRcppAdolc', flcs, element, flc)
}

test_FLCatches_set_value_accessor <- function(flcs, element, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatches_set_value_accessor', PACKAGE = 'FLRcppAdolc', flcs, element, quant, year, unit, season, area, iter, value)
}

test_FLCatches_const_get_single_index_default_accessor <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatches_const_get_single_index_default_accessor', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatches_get_single_index_default_accessor <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatches_get_single_index_default_accessor', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatches_set_single_index_default_accessor <- function(flcs, flc) {
    .Call('FLRcppAdolc_test_FLCatches_set_single_index_default_accessor', PACKAGE = 'FLRcppAdolc', flcs, flc)
}

test_FLCatchesAdolc_as_wrap <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_as_wrap', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatchesAdolc_sexp_constructor <- function(flcs_sexp1) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_sexp_constructor', PACKAGE = 'FLRcppAdolc', flcs_sexp1)
}

test_FLCatchesAdolc_FLCatchAdolc_constructor <- function(flc) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_FLCatchAdolc_constructor', PACKAGE = 'FLRcppAdolc', flc)
}

test_FLCatchesAdolc_copy_constructor <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_copy_constructor', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatchesAdolc_copy_constructor2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_copy_constructor2', PACKAGE = 'FLRcppAdolc', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAdolc_assignment_operator <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_assignment_operator', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatchesAdolc_assignment_operator2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_assignment_operator2', PACKAGE = 'FLRcppAdolc', flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAdolc_function_operator <- function(flcs, flc) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_function_operator', PACKAGE = 'FLRcppAdolc', flcs, flc)
}

test_FLCatchesAdolc_get_ncatches <- function(flc_sexp1) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_get_ncatches', PACKAGE = 'FLRcppAdolc', flc_sexp1)
}

test_FLCatchesAdolc_const_get_single_index_accessor <- function(flcs, element) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_const_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flcs, element)
}

test_FLCatchesAdolc_get_single_index_accessor <- function(flcs, element) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flcs, element)
}

test_FLCatchesAdolc_const_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_const_get_value_accessor', PACKAGE = 'FLRcppAdolc', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatchesAdolc_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_get_value_accessor', PACKAGE = 'FLRcppAdolc', flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatchesAdolc_set_single_index_accessor <- function(flcs, element, flc) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_set_single_index_accessor', PACKAGE = 'FLRcppAdolc', flcs, element, flc)
}

test_FLCatchesAdolc_set_value_accessor <- function(flcs, element, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_set_value_accessor', PACKAGE = 'FLRcppAdolc', flcs, element, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAdolc_const_get_single_index_default_accessor <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_const_get_single_index_default_accessor', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatchesAdolc_get_single_index_default_accessor <- function(flcs) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_get_single_index_default_accessor', PACKAGE = 'FLRcppAdolc', flcs)
}

test_FLCatchesAdolc_set_single_index_default_accessor <- function(flcs, flc) {
    .Call('FLRcppAdolc_test_FLCatchesAdolc_set_single_index_default_accessor', PACKAGE = 'FLRcppAdolc', flcs, flc)
}

test_FLFishery_empty_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_FLFishery_empty_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_simple_FLFishery_sexp_constructor <- function(flf_sexp) {
    .Call('FLRcppAdolc_test_simple_FLFishery_sexp_constructor', PACKAGE = 'FLRcppAdolc', flf_sexp)
}

test_FLFishery_sexp_constructor <- function(flf_sexp) {
    .Call('FLRcppAdolc_test_FLFishery_sexp_constructor', PACKAGE = 'FLRcppAdolc', flf_sexp)
}

test_FLFishery_as_wrap <- function(flf) {
    .Call('FLRcppAdolc_test_FLFishery_as_wrap', PACKAGE = 'FLRcppAdolc', flf)
}

test_FLFishery_copy_constructor <- function(flf1) {
    .Call('FLRcppAdolc_test_FLFishery_copy_constructor', PACKAGE = 'FLRcppAdolc', flf1)
}

test_FLFishery_assignment_operator <- function(flf1) {
    .Call('FLRcppAdolc_test_FLFishery_assignment_operator', PACKAGE = 'FLRcppAdolc', flf1)
}

test_FLFishery_const_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFishery_const_catches_get_accessors', PACKAGE = 'FLRcppAdolc', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFishery_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFishery_catches_get_accessors', PACKAGE = 'FLRcppAdolc', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFishery_const_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFishery_const_economics_get_accessors', PACKAGE = 'FLRcppAdolc', flf, quant, year, unit, season, area, iter)
}

test_FLFishery_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFishery_economics_get_accessors', PACKAGE = 'FLRcppAdolc', flf, quant, year, unit, season, area, iter)
}

test_FLFishery_set_accessors <- function(flf, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLFishery_set_accessors', PACKAGE = 'FLRcppAdolc', flf, catches, quant, year, unit, season, area, iter, value)
}

test_FLFishery_copy_constructor2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLFishery_copy_constructor2', PACKAGE = 'FLRcppAdolc', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFishery_assignment_operator2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLFishery_assignment_operator2', PACKAGE = 'FLRcppAdolc', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAdolc_empty_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_FLFisheryAdolc_empty_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_simple_FLFisheryAdolc_sexp_constructor <- function(flf_sexp) {
    .Call('FLRcppAdolc_test_simple_FLFisheryAdolc_sexp_constructor', PACKAGE = 'FLRcppAdolc', flf_sexp)
}

test_FLFisheryAdolc_sexp_constructor <- function(flf_sexp) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_sexp_constructor', PACKAGE = 'FLRcppAdolc', flf_sexp)
}

test_FLFisheryAdolc_as_wrap <- function(flf) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_as_wrap', PACKAGE = 'FLRcppAdolc', flf)
}

test_FLFisheryAdolc_copy_constructor <- function(flf1) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_copy_constructor', PACKAGE = 'FLRcppAdolc', flf1)
}

test_FLFisheryAdolc_assignment_operator <- function(flf1) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_assignment_operator', PACKAGE = 'FLRcppAdolc', flf1)
}

test_FLFisheryAdolc_const_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_const_catches_get_accessors', PACKAGE = 'FLRcppAdolc', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFisheryAdolc_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_catches_get_accessors', PACKAGE = 'FLRcppAdolc', flf, catches, quant, year, unit, season, area, iter)
}

test_FLFisheryAdolc_const_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_const_economics_get_accessors', PACKAGE = 'FLRcppAdolc', flf, quant, year, unit, season, area, iter)
}

test_FLFisheryAdolc_economics_get_accessors <- function(flf, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_economics_get_accessors', PACKAGE = 'FLRcppAdolc', flf, quant, year, unit, season, area, iter)
}

test_FLFisheryAdolc_set_accessors <- function(flf, catches, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_set_accessors', PACKAGE = 'FLRcppAdolc', flf, catches, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAdolc_copy_constructor2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_copy_constructor2', PACKAGE = 'FLRcppAdolc', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAdolc_assignment_operator2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLFisheryAdolc_assignment_operator2', PACKAGE = 'FLRcppAdolc', flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheries_sexp_constructor <- function(flfs_sexp1) {
    .Call('FLRcppAdolc_test_FLFisheries_sexp_constructor', PACKAGE = 'FLRcppAdolc', flfs_sexp1)
}

test_FLFisheries_as_wrap <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheries_as_wrap', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheries_get_nfisheries <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheries_get_nfisheries', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheries_copy_constructor <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheries_copy_constructor', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheries_copy_constructor2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheries_copy_constructor2', PACKAGE = 'FLRcppAdolc', flfs1, fishery, catches, indices, value)
}

test_FLFisheries_assignment_operator <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheries_assignment_operator', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheries_assignment_operator2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheries_assignment_operator2', PACKAGE = 'FLRcppAdolc', flfs1, fishery, catches, indices, value)
}

test_FLFisheries_const_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheries_const_get_single', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheries_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheries_get_single', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheries_const_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheries_const_get_double', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheries_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheries_get_double', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheries_set_single <- function(flfs, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheries_set_single', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices, value)
}

test_FLFisheries_set_double <- function(flfs, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheries_set_double', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices, value)
}

test_FLFisheriesAdolc_sexp_constructor <- function(flfs_sexp1) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_sexp_constructor', PACKAGE = 'FLRcppAdolc', flfs_sexp1)
}

test_FLFisheriesAdolc_as_wrap <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_as_wrap', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheriesAdolc_get_nfisheries <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_get_nfisheries', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheriesAdolc_copy_constructor <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_copy_constructor', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheriesAdolc_copy_constructor2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_copy_constructor2', PACKAGE = 'FLRcppAdolc', flfs1, fishery, catches, indices, value)
}

test_FLFisheriesAdolc_assignment_operator <- function(flfs) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_assignment_operator', PACKAGE = 'FLRcppAdolc', flfs)
}

test_FLFisheriesAdolc_assignment_operator2 <- function(flfs1, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_assignment_operator2', PACKAGE = 'FLRcppAdolc', flfs1, fishery, catches, indices, value)
}

test_FLFisheriesAdolc_const_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_const_get_single', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheriesAdolc_get_single <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_get_single', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheriesAdolc_const_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_const_get_double', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheriesAdolc_get_double <- function(flfs, fishery, catches, indices) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_get_double', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices)
}

test_FLFisheriesAdolc_set_single <- function(flfs, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_set_single', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices, value)
}

test_FLFisheriesAdolc_set_double <- function(flfs, fishery, catches, indices, value) {
    .Call('FLRcppAdolc_test_FLFisheriesAdolc_set_double', PACKAGE = 'FLRcppAdolc', flfs, fishery, catches, indices, value)
}

test_FLQuantAdolc_as_wrap <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_as_wrap', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_basic_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_FLQuantAdolc_basic_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_FLQuantAdolc_sexp_constructor <- function(flq_sexp) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_sexp_constructor', PACKAGE = 'FLRcppAdolc', flq_sexp)
}

test_FLQuantAdolc_dim_constructor <- function(nquant, nyear, nunit, nseason, narea, niter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_dim_constructor', PACKAGE = 'FLRcppAdolc', nquant, nyear, nunit, nseason, narea, niter)
}

test_FLQuantAdolc_copy_constructor <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_copy_constructor', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_copy_constructor2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_copy_constructor2', PACKAGE = 'FLRcppAdolc', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuantAdolc_assignment_operator <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_assignment_operator', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_assignment_operator2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_assignment_operator2', PACKAGE = 'FLRcppAdolc', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuantAdolc_from_FLQuant_constructor <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_from_FLQuant_constructor', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_units <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_units', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_dim <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_dim', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_dimnames <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_dimnames', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_size <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_size', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_nquant <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_nquant', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_nyear <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_nyear', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_nunit <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_nunit', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_nseason <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_nseason', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_narea <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_narea', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_niter <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_niter', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc_get_data_element <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_data_element', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter)
}

test_FLQuantAdolc_get_const_single_index_accessor <- function(flq, element) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_const_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element)
}

test_FLQuantAdolc_get_single_index_accessor <- function(flq, element) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element)
}

test_FLQuantAdolc_set_single_index_accessor <- function(flq, element, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_set_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element, value)
}

test_FLQuantAdolc_const_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_const_get_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter)
}

test_FLQuantAdolc_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter)
}

test_FLQuantAdolc_set_accessor <- function(flq, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_set_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter, value)
}

test_FLQuantAdolc_get_const_indices_accessor <- function(flq, indices) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_const_indices_accessor', PACKAGE = 'FLRcppAdolc', flq, indices)
}

test_FLQuantAdolc_get_indices_accessor <- function(flq, indices) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_get_indices_accessor', PACKAGE = 'FLRcppAdolc', flq, indices)
}

test_FLQuantAdolc_set_indices_accessor <- function(flq, indices, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_set_indices_accessor', PACKAGE = 'FLRcppAdolc', flq, indices, value)
}

test_FLQuantAdolc_set_dimnames <- function(flq, new_dimnames) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_set_dimnames', PACKAGE = 'FLRcppAdolc', flq, new_dimnames)
}

test_FLQuantAdolc_FLQuantAdolc_match_dims <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuantAdolc_match_dims', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuantAdolc_FLQuant_match_dims <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuantAdolc_FLQuant_match_dims', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_FLQuantAdolc_match_dims <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuantAdolc_match_dims', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_as_wrap <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_as_wrap', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_basic_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_FLQuant_basic_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_FLQuant_sexp_constructor <- function(flq_sexp) {
    .Call('FLRcppAdolc_test_FLQuant_sexp_constructor', PACKAGE = 'FLRcppAdolc', flq_sexp)
}

test_FLQuant_dim_constructor <- function(nquant, nyear, nunit, nseason, narea, niter) {
    .Call('FLRcppAdolc_test_FLQuant_dim_constructor', PACKAGE = 'FLRcppAdolc', nquant, nyear, nunit, nseason, narea, niter)
}

test_FLQuant_copy_constructor <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_copy_constructor', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_copy_constructor2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant_copy_constructor2', PACKAGE = 'FLRcppAdolc', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_assignment_operator <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_assignment_operator', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_assignment_operator2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant_assignment_operator2', PACKAGE = 'FLRcppAdolc', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_get_data <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_data', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_units <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_units', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_dim <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_dim', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_dimnames <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_dimnames', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_dimnames2 <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_dimnames2', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_size <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_size', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_nquant <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nquant', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_nyear <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nyear', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_nunit <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nunit', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_nseason <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nseason', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_narea <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_narea', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_niter <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_niter', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_data_element <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant_get_data_element', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter)
}

test_FLQuant_get_const_single_index_accessor <- function(flq, element) {
    .Call('FLRcppAdolc_test_FLQuant_get_const_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element)
}

test_FLQuant_get_single_index_accessor <- function(flq, element) {
    .Call('FLRcppAdolc_test_FLQuant_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element)
}

test_FLQuant_set_single_index_accessor <- function(flq, element, value) {
    .Call('FLRcppAdolc_test_FLQuant_set_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element, value)
}

test_FLQuant_const_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant_const_get_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter)
}

test_FLQuant_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant_get_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter)
}

test_FLQuant_set_accessor <- function(flq, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant_set_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter, value)
}

test_FLQuant_get_const_indices_accessor <- function(flq, indices) {
    .Call('FLRcppAdolc_test_FLQuant_get_const_indices_accessor', PACKAGE = 'FLRcppAdolc', flq, indices)
}

test_FLQuant_get_indices_accessor <- function(flq, indices) {
    .Call('FLRcppAdolc_test_FLQuant_get_indices_accessor', PACKAGE = 'FLRcppAdolc', flq, indices)
}

test_FLQuant_set_indices_accessor <- function(flq, indices, value) {
    .Call('FLRcppAdolc_test_FLQuant_set_indices_accessor', PACKAGE = 'FLRcppAdolc', flq, indices, value)
}

test_FLQuant_get_all_iters <- function(flq, quant, year, unit, season, area) {
    .Call('FLRcppAdolc_test_FLQuant_get_all_iters', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area)
}

test_FLQuant_set_data <- function(flq, data_in) {
    .Call('FLRcppAdolc_test_FLQuant_set_data', PACKAGE = 'FLRcppAdolc', flq, data_in)
}

test_FLQuant_set_dimnames <- function(flq, new_dimnames) {
    .Call('FLRcppAdolc_test_FLQuant_set_dimnames', PACKAGE = 'FLRcppAdolc', flq, new_dimnames)
}

test_FLQuant_set_units <- function(flq, new_units) {
    .Call('FLRcppAdolc_test_FLQuant_set_units', PACKAGE = 'FLRcppAdolc', flq, new_units)
}

test_FLQuant_subset <- function(flq, quant_min, quant_max, year_min, year_max, unit_min, unit_max, season_min, season_max, area_min, area_max, iter_min, iter_max) {
    .Call('FLRcppAdolc_test_FLQuant_subset', PACKAGE = 'FLRcppAdolc', flq, quant_min, quant_max, year_min, year_max, unit_min, unit_max, season_min, season_max, area_min, area_max, iter_min, iter_max)
}

test_FLQuant_propagate_iters <- function(flq, iters) {
    .Call('FLRcppAdolc_test_FLQuant_propagate_iters', PACKAGE = 'FLRcppAdolc', flq, iters)
}

test_FLQuant_FLQuant_match_dims <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_match_dims', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant7_as_wrap <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuant7_as_wrap', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuant7_empty_wrap <- function() {
    .Call('FLRcppAdolc_test_FLQuant7_empty_wrap', PACKAGE = 'FLRcppAdolc')
}

test_FLQuant7_basic_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_FLQuant7_basic_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_FLQuant7_sexp_constructor <- function(flq_sexp1) {
    .Call('FLRcppAdolc_test_FLQuant7_sexp_constructor', PACKAGE = 'FLRcppAdolc', flq_sexp1)
}

test_FLQuant7_FLQuant_constructor <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant7_FLQuant_constructor', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant7_copy_constructor <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuant7_copy_constructor', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuant7_copy_constructor2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant7_copy_constructor2', PACKAGE = 'FLRcppAdolc', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_assignment_operator <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuant7_assignment_operator', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuant7_assignment_operator2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant7_assignment_operator2', PACKAGE = 'FLRcppAdolc', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_function_operator <- function(flq7, flq) {
    .Call('FLRcppAdolc_test_FLQuant7_function_operator', PACKAGE = 'FLRcppAdolc', flq7, flq)
}

test_FLQuant7_get_ndim7 <- function(flq_sexp1) {
    .Call('FLRcppAdolc_test_FLQuant7_get_ndim7', PACKAGE = 'FLRcppAdolc', flq_sexp1)
}

test_FLQuant7_const_get_single_index_accessor <- function(flq7, element) {
    .Call('FLRcppAdolc_test_FLQuant7_const_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq7, element)
}

test_FLQuant7_get_single_index_accessor <- function(flq7, element) {
    .Call('FLRcppAdolc_test_FLQuant7_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq7, element)
}

test_FLQuant7_set_single_index_accessor <- function(flq7, element, flq) {
    .Call('FLRcppAdolc_test_FLQuant7_set_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq7, element, flq)
}

test_FLQuant7_const_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant7_const_get_accessor', PACKAGE = 'FLRcppAdolc', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant7_get_accessor', PACKAGE = 'FLRcppAdolc', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7_set_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant7_set_accessor', PACKAGE = 'FLRcppAdolc', flq7, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_const_default_dim7_get_accessor <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuant7_const_default_dim7_get_accessor', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuant7_default_dim7_get_accessor <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuant7_default_dim7_get_accessor', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuant7_default_dim7_set_accessor <- function(flq7, flq) {
    .Call('FLRcppAdolc_test_FLQuant7_default_dim7_set_accessor', PACKAGE = 'FLRcppAdolc', flq7, flq)
}

test_FLQuant7_const_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant7_const_default_dim7_get_accessor_multi', PACKAGE = 'FLRcppAdolc', flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant7_default_dim7_get_accessor_multi', PACKAGE = 'FLRcppAdolc', flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7_default_dim7_set_accessor_multi <- function(flq7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant7_default_dim7_set_accessor_multi', PACKAGE = 'FLRcppAdolc', flq7, quant, year, unit, season, area, iter, value)
}

test_FLQuantAdolc7_as_wrap <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_as_wrap', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuantAdolc7_empty_wrap <- function() {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_empty_wrap', PACKAGE = 'FLRcppAdolc')
}

test_FLQuantAdolc7_basic_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_FLQuantAdolc7_basic_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_FLQuantAdolc7_sexp_constructor <- function(flq_sexp1) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_sexp_constructor', PACKAGE = 'FLRcppAdolc', flq_sexp1)
}

test_FLQuantAdolc7_FLQuant_constructor <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_FLQuant_constructor', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuantAdolc7_copy_constructor <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_copy_constructor', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuantAdolc7_copy_constructor2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_copy_constructor2', PACKAGE = 'FLRcppAdolc', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuantAdolc7_assignment_operator <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_assignment_operator', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuantAdolc7_assignment_operator2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_assignment_operator2', PACKAGE = 'FLRcppAdolc', flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuantAdolc7_function_operator <- function(flq7, flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_function_operator', PACKAGE = 'FLRcppAdolc', flq7, flq)
}

test_FLQuantAdolc7_get_ndim7 <- function(flq_sexp1) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_get_ndim7', PACKAGE = 'FLRcppAdolc', flq_sexp1)
}

test_FLQuantAdolc7_const_get_single_index_accessor <- function(flq7, element) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_const_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq7, element)
}

test_FLQuantAdolc7_get_single_index_accessor <- function(flq7, element) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq7, element)
}

test_FLQuantAdolc7_set_single_index_accessor <- function(flq7, element, flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_set_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq7, element, flq)
}

test_FLQuantAdolc7_const_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_const_get_accessor', PACKAGE = 'FLRcppAdolc', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuantAdolc7_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_get_accessor', PACKAGE = 'FLRcppAdolc', flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuantAdolc7_set_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_set_accessor', PACKAGE = 'FLRcppAdolc', flq7, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuantAdolc7_const_default_dim7_get_accessor <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_const_default_dim7_get_accessor', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuantAdolc7_default_dim7_get_accessor <- function(flq7) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_default_dim7_get_accessor', PACKAGE = 'FLRcppAdolc', flq7)
}

test_FLQuantAdolc7_default_dim7_set_accessor <- function(flq7, flq) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_default_dim7_set_accessor', PACKAGE = 'FLRcppAdolc', flq7, flq)
}

test_FLQuantAdolc7_const_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_const_default_dim7_get_accessor_multi', PACKAGE = 'FLRcppAdolc', flq7, quant, year, unit, season, area, iter)
}

test_FLQuantAdolc7_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_default_dim7_get_accessor_multi', PACKAGE = 'FLRcppAdolc', flq7, quant, year, unit, season, area, iter)
}

test_FLQuantAdolc7_default_dim7_set_accessor_multi <- function(flq7, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuantAdolc7_default_dim7_set_accessor_multi', PACKAGE = 'FLRcppAdolc', flq7, quant, year, unit, season, area, iter, value)
}

test_FLQ_in_FLS <- function(flq) {
    .Call('FLRcppAdolc_test_FLQ_in_FLS', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLStock_sexp_constructor <- function(fls_sexp) {
    .Call('FLRcppAdolc_test_FLStock_sexp_constructor', PACKAGE = 'FLRcppAdolc', fls_sexp)
}

test_FLStock_wrap <- function(fls_sexp) {
    .Call('FLRcppAdolc_test_FLStock_wrap', PACKAGE = 'FLRcppAdolc', fls_sexp)
}

test_FLStock_as <- function(fls) {
    .Call('FLRcppAdolc_test_FLStock_as', PACKAGE = 'FLRcppAdolc', fls)
}

test_FLStock_as_wrap <- function(fls) {
    .Call('FLRcppAdolc_test_FLStock_as_wrap', PACKAGE = 'FLRcppAdolc', fls)
}

test_FLStock_copy_constructor <- function(fls1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLStock_copy_constructor', PACKAGE = 'FLRcppAdolc', fls1, quant, year, unit, season, area, iter, value)
}

test_FLStock_assignment_operator <- function(fls1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLStock_assignment_operator', PACKAGE = 'FLRcppAdolc', fls1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_sexp_constructor <- function(flb_sexp) {
    .Call('FLRcppAdolc_test_fwdBiol_sexp_constructor', PACKAGE = 'FLRcppAdolc', flb_sexp)
}

test_fwdBiolAdolc_sexp_constructor <- function(flb_sexp) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_sexp_constructor', PACKAGE = 'FLRcppAdolc', flb_sexp)
}

test_fwdBiol_as_wrap <- function(fwdb) {
    .Call('FLRcppAdolc_test_fwdBiol_as_wrap', PACKAGE = 'FLRcppAdolc', fwdb)
}

test_fwdBiolAdolc_as_wrap <- function(fwdb) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_as_wrap', PACKAGE = 'FLRcppAdolc', fwdb)
}

test_fwdBiol_fwdSR_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call('FLRcppAdolc_test_fwdBiol_fwdSR_constructor', PACKAGE = 'FLRcppAdolc', flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiol_FLSR_bits_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call('FLRcppAdolc_test_fwdBiol_FLSR_bits_constructor', PACKAGE = 'FLRcppAdolc', flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiolAdolc_fwdSRAdolc_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_fwdSRAdolc_constructor', PACKAGE = 'FLRcppAdolc', flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiolAdolc_FLSR_bits_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_FLSR_bits_constructor', PACKAGE = 'FLRcppAdolc', flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiol_copy_constructor <- function(fwdb1) {
    .Call('FLRcppAdolc_test_fwdBiol_copy_constructor', PACKAGE = 'FLRcppAdolc', fwdb1)
}

test_fwdBiolAdolc_copy_constructor <- function(fwdb1) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_copy_constructor', PACKAGE = 'FLRcppAdolc', fwdb1)
}

test_fwdBiol_copy_constructor2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_fwdBiol_copy_constructor2', PACKAGE = 'FLRcppAdolc', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiolAdolc_copy_constructor2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_copy_constructor2', PACKAGE = 'FLRcppAdolc', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_assignment_operator <- function(fwdb1) {
    .Call('FLRcppAdolc_test_fwdBiol_assignment_operator', PACKAGE = 'FLRcppAdolc', fwdb1)
}

test_fwdBiolAdolc_assignment_operator <- function(fwdb1) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_assignment_operator', PACKAGE = 'FLRcppAdolc', fwdb1)
}

test_fwdBiol_assignment_operator2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_fwdBiol_assignment_operator2', PACKAGE = 'FLRcppAdolc', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiolAdolc_assignment_operator2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_assignment_operator2', PACKAGE = 'FLRcppAdolc', fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_const_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_fwdBiol_const_get_accessors', PACKAGE = 'FLRcppAdolc', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiol_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_fwdBiol_get_accessors', PACKAGE = 'FLRcppAdolc', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiolAdolc_const_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_const_get_accessors', PACKAGE = 'FLRcppAdolc', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiolAdolc_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_get_accessors', PACKAGE = 'FLRcppAdolc', fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiol_set_accessors <- function(fwdb, quant, year, unit, season, area, iter, values) {
    .Call('FLRcppAdolc_test_fwdBiol_set_accessors', PACKAGE = 'FLRcppAdolc', fwdb, quant, year, unit, season, area, iter, values)
}

test_fwdBiolAdolc_set_accessors <- function(fwdb, quant, year, unit, season, area, iter, values) {
    .Call('FLRcppAdolc_test_fwdBiolAdolc_set_accessors', PACKAGE = 'FLRcppAdolc', fwdb, quant, year, unit, season, area, iter, values)
}

test_fwdSR_empty_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_fwdSR_empty_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_fwdSR_constructor_wrap <- function(model_name, params, residuals, residuals_mult) {
    .Call('FLRcppAdolc_test_fwdSR_constructor_wrap', PACKAGE = 'FLRcppAdolc', model_name, params, residuals, residuals_mult)
}

test_fwdSR_constructor_value <- function(model_name, params, residuals, residuals_mult) {
    .Call('FLRcppAdolc_test_fwdSR_constructor_value', PACKAGE = 'FLRcppAdolc', model_name, params, residuals, residuals_mult)
}

test_fwdSR_get_nparams <- function(model_name, params, residuals, residuals_mult) {
    .Call('FLRcppAdolc_test_fwdSR_get_nparams', PACKAGE = 'FLRcppAdolc', model_name, params, residuals, residuals_mult)
}

test_fwdSR_eval_simple <- function(model_name, params, residuals, residuals_mult, ssb) {
    .Call('FLRcppAdolc_test_fwdSR_eval_simple', PACKAGE = 'FLRcppAdolc', model_name, params, residuals, residuals_mult, ssb)
}

test_fwdSR_copy_constructor <- function(model_name, params, residuals, residuals_mult, ssb) {
    .Call('FLRcppAdolc_test_fwdSR_copy_constructor', PACKAGE = 'FLRcppAdolc', model_name, params, residuals, residuals_mult, ssb)
}

test_fwdSR_assignment_operator <- function(model_name, params, residuals, residuals_mult, ssb) {
    .Call('FLRcppAdolc_test_fwdSR_assignment_operator', PACKAGE = 'FLRcppAdolc', model_name, params, residuals, residuals_mult, ssb)
}

test_operatingModel_empty_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_operatingModel_empty_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_operatingModelAdolc_empty_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_operatingModelAdolc_empty_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_operatingModel_full_constructor <- function(flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn) {
    .Call('FLRcppAdolc_test_operatingModel_full_constructor', PACKAGE = 'FLRcppAdolc', flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn)
}

test_operatingModel_SSB_FLQ <- function(flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn) {
    .Call('FLRcppAdolc_test_operatingModel_SSB_FLQ', PACKAGE = 'FLRcppAdolc', flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn)
}

test_operatingModelAdolc_SSB_FLQ <- function(flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn) {
    .Call('FLRcppAdolc_test_operatingModelAdolc_SSB_FLQ', PACKAGE = 'FLRcppAdolc', flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn)
}

test_operatingModel_SSB_iters <- function(flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn, timestep, unit, area) {
    .Call('FLRcppAdolc_test_operatingModel_SSB_iters', PACKAGE = 'FLRcppAdolc', flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn, timestep, unit, area)
}

test_operatingModel_SSB_single_iter <- function(flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn, timestep, unit, area, iter) {
    .Call('FLRcppAdolc_test_operatingModel_SSB_single_iter', PACKAGE = 'FLRcppAdolc', flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn, timestep, unit, area, iter)
}

test_operating_model_project <- function(flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn, timestep) {
    .Call('FLRcppAdolc_test_operating_model_project', PACKAGE = 'FLRcppAdolc', flfs, flb_sexp, model_name, params, residuals, residuals_mult, f, f_spwn, timestep)
}

test_year_season_to_timestep_FLQuant_double <- function(flq, year, season) {
    .Call('FLRcppAdolc_test_year_season_to_timestep_FLQuant_double', PACKAGE = 'FLRcppAdolc', flq, year, season)
}

test_year_season_to_timestep_FLQuant_adouble <- function(flqad, year, season) {
    .Call('FLRcppAdolc_test_year_season_to_timestep_FLQuant_adouble', PACKAGE = 'FLRcppAdolc', flqad, year, season)
}

test_timestep_to_year_season_FLQuant_double <- function(flq, timestep) {
    .Call('FLRcppAdolc_test_timestep_to_year_season_FLQuant_double', PACKAGE = 'FLRcppAdolc', flq, timestep)
}

test_timestep_to_year_season_FLQuant_adouble <- function(flqad, timestep) {
    .Call('FLRcppAdolc_test_timestep_to_year_season_FLQuant_adouble', PACKAGE = 'FLRcppAdolc', flqad, timestep)
}

test_euclid_norm <- function(xvec) {
    .Call('FLRcppAdolc_test_euclid_norm', PACKAGE = 'FLRcppAdolc', xvec)
}

test_NR1 <- function(initial_value, max_iters, max_limit, tolerance) {
    .Call('FLRcppAdolc_test_NR1', PACKAGE = 'FLRcppAdolc', initial_value, max_iters, max_limit, tolerance)
}

test_NR2 <- function(initial_value, max_iters, max_limit, tolerance) {
    .Call('FLRcppAdolc_test_NR2', PACKAGE = 'FLRcppAdolc', initial_value, max_iters, max_limit, tolerance)
}

