# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_nothing_FLQuantAdolc <- function() {
    invisible(.Call('FLRcppAdolc_do_nothing_FLQuantAdolc', PACKAGE = 'FLRcppAdolc'))
}

do_nothing_FLQuant <- function() {
    invisible(.Call('FLRcppAdolc_do_nothing_FLQuant', PACKAGE = 'FLRcppAdolc'))
}

test_FLQuant_basic_constructor <- function() {
    invisible(.Call('FLRcppAdolc_test_FLQuant_basic_constructor', PACKAGE = 'FLRcppAdolc'))
}

test_FLQuant_sexp_constructor <- function(flq_sexp) {
    invisible(.Call('FLRcppAdolc_test_FLQuant_sexp_constructor', PACKAGE = 'FLRcppAdolc', flq_sexp))
}

test_FLQuant_as_wrap <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_as_wrap', PACKAGE = 'FLRcppAdolc', flq)
}

test_mult <- function() {
    invisible(.Call('FLRcppAdolc_test_mult', PACKAGE = 'FLRcppAdolc'))
}

