# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_FLQuant_as_wrap <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_as_wrap', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_sexp_constructor <- function(flq_sexp) {
    .Call('FLRcppAdolc_test_FLQuant_sexp_constructor', PACKAGE = 'FLRcppAdolc', flq_sexp)
}

test_FLQuant_copy_constructor <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant_copy_constructor', PACKAGE = 'FLRcppAdolc', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_assignment_operator <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_get_units <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_units', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_set_units <- function(flq, new_units) {
    .Call('FLRcppAdolc_test_FLQuant_set_units', PACKAGE = 'FLRcppAdolc', flq, new_units)
}

test_FLQuant_get_data <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_data', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_set_data <- function(flq, data_in) {
    .Call('FLRcppAdolc_test_FLQuant_set_data', PACKAGE = 'FLRcppAdolc', flq, data_in)
}

test_FLQuant_get_nquant <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nquant', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_nyear <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nyear', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_nunit <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nunit', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_nseason <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_nseason', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_narea <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_narea', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_niter <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_niter', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_dim <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_dim', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_set_dim <- function(flq, dim) {
    .Call('FLRcppAdolc_test_FLQuant_set_dim', PACKAGE = 'FLRcppAdolc', flq, dim)
}

test_FLQuant_get_dimnames <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_get_dimnames', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call('FLRcppAdolc_test_FLQuant_get_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter)
}

test_FLQuant_get_single_index_accessor <- function(flq, element) {
    .Call('FLRcppAdolc_test_FLQuant_get_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element)
}

test_FLQuant_get_single_index_accessor2 <- function(flq, element) {
    .Call('FLRcppAdolc_test_FLQuant_get_single_index_accessor2', PACKAGE = 'FLRcppAdolc', flq, element)
}

test_FLQuant_set_accessor <- function(flq, quant, year, unit, season, area, iter, value) {
    .Call('FLRcppAdolc_test_FLQuant_set_accessor', PACKAGE = 'FLRcppAdolc', flq, quant, year, unit, season, area, iter, value)
}

test_FLQuant_set_single_index_accessor <- function(flq, element, value) {
    .Call('FLRcppAdolc_test_FLQuant_set_single_index_accessor', PACKAGE = 'FLRcppAdolc', flq, element, value)
}

test_FLQuant_match_dims <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_match_dims', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_FLQuant_multiplier_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_FLQuant_multiplier_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_double_multiplier_assignment_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_multiplier_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_double_multiplier_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_multiplier_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_FLQuant_multiplier_uses_deep_copy <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_multiplier_uses_deep_copy', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_FLQuant_divide_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_divide_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_FLQuant_divide_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_divide_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_double_divide_assignment_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_divide_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_double_divide_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_divide_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_FLQuant_addition_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_FLQuant_addition_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_double_addition_assignment_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_addition_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_double_addition_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_addition_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_FLQuant_difference_assignment_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_difference_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_FLQuant_difference_operator <- function(flq1, flq2) {
    .Call('FLRcppAdolc_test_FLQuant_FLQuant_difference_operator', PACKAGE = 'FLRcppAdolc', flq1, flq2)
}

test_FLQuant_double_difference_assignment_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_difference_assignment_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_double_difference_operator <- function(flq1, rhs) {
    .Call('FLRcppAdolc_test_FLQuant_double_difference_operator', PACKAGE = 'FLRcppAdolc', flq1, rhs)
}

test_FLQuant_log_function <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_log_function', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_exp_function <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_exp_function', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLQuant_chaining_operators <- function(flq) {
    .Call('FLRcppAdolc_test_FLQuant_chaining_operators', PACKAGE = 'FLRcppAdolc', flq)
}

test_FLStock_as <- function(fls) {
    .Call('FLRcppAdolc_test_FLStock_as', PACKAGE = 'FLRcppAdolc', fls)
}

test_FLStock_wrap <- function(fls_sexp) {
    .Call('FLRcppAdolc_test_FLStock_wrap', PACKAGE = 'FLRcppAdolc', fls_sexp)
}

test_FLStock_sexp_constructor <- function(fls_sexp) {
    .Call('FLRcppAdolc_test_FLStock_sexp_constructor', PACKAGE = 'FLRcppAdolc', fls_sexp)
}

